// <auto-generated />
using System;
using Europhonium.Shared.Infrastructure.DataAccess.EFCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Europhonium.Shared.Infrastructure.DataAccess.EFCore.Migrations
{
    [DbContext(typeof(WebAppDbContext))]
    [Migration("20241209112753_Add-Country-Entity")]
    partial class AddCountryEntity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Europhonium.Shared.Domain.Countries.Country", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasColumnType("char(2)")
                        .HasColumnName("country_code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_country");

                    b.HasIndex("CountryCode")
                        .IsUnique()
                        .HasDatabaseName("ix_country_country_code");

                    b.ToTable("country", (string)null);
                });

            modelBuilder.Entity("Europhonium.Shared.Domain.Countries.Country", b =>
                {
                    b.OwnsMany("Europhonium.Shared.Domain.Contests.ContestId", "ParticipatingContestIds", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasColumnName("id");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<Guid>("CountryId")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("country_id");

                            b1.Property<Guid>("Value")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("participating_contest_id");

                            b1.HasKey("Id")
                                .HasName("pk_country_participating_contest");

                            b1.HasIndex("CountryId", "Value")
                                .IsUnique()
                                .HasDatabaseName("ix_country_participating_contest_country_id_participating_contest_id");

                            b1.ToTable("country_participating_contest", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("CountryId")
                                .HasConstraintName("fk_country_participating_contest_country_country_id");
                        });

                    b.OwnsMany("Europhonium.Shared.Domain.Broadcasts.BroadcastId", "CompetingBroadcastIds", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasColumnName("id");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<Guid>("CountryId")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("country_id");

                            b1.Property<Guid>("Value")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("competing_broadcast_id");

                            b1.HasKey("Id");

                            b1.HasIndex("CountryId", "Value")
                                .IsUnique()
                                .HasDatabaseName("ix_country_competing_broadcast_country_id_competing_broadcast_id");

                            b1.ToTable("country_competing_broadcast", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("CountryId")
                                .HasConstraintName("fk_country_competing_broadcast_country_country_id");
                        });

                    b.OwnsMany("Europhonium.Shared.Domain.Broadcasts.BroadcastId", "VotingBroadcastIds", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasColumnName("id");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<Guid>("CountryId")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("country_id");

                            b1.Property<Guid>("Value")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("voting_broadcast_id");

                            b1.HasKey("Id")
                                .HasName("pk_country_voting_broadcast");

                            b1.HasIndex("CountryId", "Value")
                                .IsUnique()
                                .HasDatabaseName("ix_country_voting_broadcast_country_id_voting_broadcast_id");

                            b1.ToTable("country_voting_broadcast", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("CountryId")
                                .HasConstraintName("fk_country_voting_broadcast_country_country_id");
                        });

                    b.Navigation("CompetingBroadcastIds");

                    b.Navigation("ParticipatingContestIds");

                    b.Navigation("VotingBroadcastIds");
                });
#pragma warning restore 612, 618
        }
    }
}
