# Publish and Deploy Europhonium.WebApi to Azure App Service

name: Publish and Deploy Europhonium API

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  AZURE_WEBAPP_NAME: europhonium
  AZURE_WEBAPP_PACKAGE_PATH: src\Europhonium.WebApi\published
  CONFIGURATION: Release
  DOTNET_VERSION: 8.0.x
  PROJECT_DIR: src\Europhonium.WebApi

jobs:
  publish:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      - name: Restore
        run: dotnet restore "${{ env.PROJECT_DIR }}"
      - name: Build
        run: dotnet build "${{ env.PROJECT_DIR }}" --configuration ${{ env.CONFIGURATION }} --no-restore
      - name: Test
        run: dotnet "${{ env.PROJECT_DIR }}" --no-build
      - name: Publish
        run: dotnet publish "${{ env.PROJECT_DIR }}" --configuration ${{ env.CONFIGURATION }} --no-build --output "${{ env.AZURE_WEBAPP_PACKAGE_PATH }}"
      - name: Publish Artifact
        uses: actions/upload-artifact@v4
        with:
          name: webapp
          path: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
          retention-days: 7
